[package]
name = "regex-to-json-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-syntax = "0.6"
clap = { version = "3.1", features = ["derive"] }
schemars = "0.8"
serde_json = "1"
